---
url: https://www.emfink.net # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
title: Eric M. Fink
description:  # leave blank if you don't want to display a description 
last_updated: 3 January 2021 # leave blank if you don't want to display last updated

name: Eric M. Fink
city: Greensboro
state: North Carolina
email: emfink@gmail.com
phone: 336-279-9334

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
