---
url: https://www.emfink.net # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
title: Eric M. Fink
description:  # leave blank if you don't want to display a description 
last_updated: 7 January 2021 # leave blank if you don't want to display last updated

author: Eric M. Fink
position: Associate Professor
institution: Elon Law School
city: Greensboro
state: North Carolina
email: emfink@gmail.com
phone: 336-279-9334


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings

# deployment
host: localhost
port: 4000


markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
include: ['_pages']
exclude: ['Gemfile.lock', .admin]
keep_files: [.admin]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/EricMFink.github.com/

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
